import 'package:drift/drift.dart';
/// EVENT LAYER (ADAS DECISIONS)
/// 
/// Stores important safety events generated by the system.
///
/// Used for:
/// • Safety auditing
/// • Driver feedback
/// • Risk analysis
/// • Debugging AI decisions

@TableIndex(name: 'event_time_idx', columns: {#timestamp})
@TableIndex(name: 'event_session_idx', columns: {#sessionId})
@TableIndex(name: 'event_type_idx', columns: {#eventType})
class DrivingEvents extends Table {

  IntColumn get id => integer().autoIncrement()();

  DateTimeColumn get timestamp => dateTime()();

  TextColumn get sessionId => text().nullable()();

  TextColumn get eventType => text()();

  RealColumn get severity => real()();

  RealColumn get confidence => real()();

  RealColumn get latitude => real().nullable()();
  RealColumn get longitude => real().nullable()();

  TextColumn get metadata => text().nullable()();
}